### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by DonaldTsang** [fire-eggs/Danbooru2019#45]
Is it possible to save the data into PostgreSQL instead, so that tag embedding can be done and compared between Danbooru and Derpibooru?

Cross-referencing: https://github.com/fire-eggs/Danbooru2019/tree/master/database and https://derpibooru.org/pages/data_dumps
Goal: https://www.aclweb.org/anthology/L18-1156.pdf

**Comment by fire-eggs** [comment]
Certainly! makedb.py creates the database with basic SQL commands. That program can be modified  using a Postgres package (e.g. [psycopg2](https://pypi.org/project/psycopg2/)) and the appropriate Postgres-specific SQL commands.

Looking at the schema from [Derpibooru](https://derpibooru.org/pages/data_dumps), it looks like it would be fairly straightforward to use it:
- Derp's "public.images" looks like a close match to makedb's "images" table.
- Derp's "public.tags" corresponds to makedb's "tags" table. You'd have to assign some appropriate value for the 'slug' and 'category' columns, based on Derp's data dump.
- Derp's "public.tag_changes" appears to be the correspondent for makedb's "imageTags" table. In [Gwern's metadata](https://www.gwern.net/Danbooru2020#image-metadata), only the image_id and tag_id columns are available; you'd need to assign appropriate values for the other columns.

Gwern's metadata doesn't readily permit any of the other tables in the Derpibooru schema to be populated. I'm unsure if you need any of those tables for your goals.

**Comment by DonaldTsang** [comment]
First, what is the process for converting SQLite to PostgreSQL?

Also I have discovered something about my needs for Tag Implications (and Tag Alias Cleaning): 
- https://danbooru.donmai.us/wiki_pages/help:tag_implications (for reference usage)
- https://danbooru.donmai.us/posts?tags=help%3Atag_aliases (might be needed for data cleaning)
these two are not in the DB schema atm.

> Tag aliases differ from implications, where both tags remain on the image. In other words, aliases are for tags referring to the same thing, while implications are for situations where one tag describes a subset of the images belonging to another tag.

Am already using DerpiDB for doing Co-occurrence tasks.

**Comment by fire-eggs** [comment]
History suggests the Danbooru server itself was using PostgreSQL. If that is still the case, asking the Danbooru maintainers for a copy of the database would be the most expeditious method for PostgreSQL support.

I don't have PostgreSQL and don't have the background to support it.

**Comment by fire-eggs** [comment]
A possible solution: https://github.com/bitdotioinc/pgsqlite
