### ISSUE TITLE
[Question] Rsyncing the dataset with WSL

### ISSUE THREAD

**Issue by Kelhsy** [fire-eggs/Danbooru2019#54]
Considering I have a Windows server with the Linux Subsystem, is the dataset and the files (Windows doesn't like certain characters in file names that linux supports) compatible with and will I be able to sync the dataset with rsync onto my NTFS formatted drive?

**Comment by fire-eggs** [comment]
Hi, I've not found any special characters in gwern's dataset. The folders are numbers from 0000 to 0999 ; the filenames are all numeric; even the raw metadata files don't use special characters!

When I first downloaded the dataset (Danbooru2018) I did so on my Windows NTFS box.

Hope that helps!

**Comment by Kelhsy** [comment]
Yes it has, thank you, I managed to pull the entire dataset, even if at times error 12 came up I seem to have everything!
